version: '3.7'

services:
  nginx:
    image: sfcontainer.azurecr.io/symfony-demo_nginx
    volumes:
      - ./assets:/app/web
    depends_on:
      - php-fpm
    ports:
      - 8000:80
  php-fpm:
    image: sfcontainer.azurecr.io/symfony-demo_php-fpm
    volumes:
      - .:/app
    command: sh -c 'composer install --ignore-platform-reqs && php-fpm'
  #   depends_on:
  #     - mysql
  # mysql:
  #   build:
  #     args:
  #       VERSION: $MYSQL_VERSION
  #     context: ./docker/mysql
  #   environment:
  #     MYSQL_DATABASE: $MYSQL_DATABASE
  #     MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
  #   volumes:
  #     - ./docker/mysql/data:/var/lib/mysql
